### ISSUE TITLE
Disable default-features of image crate

### ISSUE THREAD

**Issue by Aloxaf** [image-rs/imageproc#344]
'imageproc' doesn't seem to depend on the specific features of 'image' to work.

Adding `default-features = false` for 'image' and just enabling it in `[dev-dependencies]` will be good, otherwise, we couldn't control the features of 'image' if we depend on 'imageproc'

eg.
```toml
[dependencies]
image = { version = "0.21.0", default-features = false }

[dev-dependencies]
image = "0.21.0"
```
