### ISSUE TITLE
Bug with `imageproc::drawing::draw_text`?

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [image-rs/imageproc#472]
### [test_project.zip](https://github.com/image-rs/imageproc/files/7339122/test_project.zip)

So I was looking into drawing some text on an image:

`src/main.rs`:

```rust
fn main() {
    const SIZE: u32 = 500;
    let mut img_buf: image::RgbImage = image::ImageBuffer::from_raw(
        SIZE, 
        SIZE, 
        (0..SIZE*SIZE).flat_map(|_|vec![255,255,255]).collect::<Vec<u8>>()
    ).unwrap();
    img_buf.save("img_blank.png").unwrap();

    const TEXT: &'static str = "Placeholder";
    const TEXT_COLOR: image::Rgb<u8> = image::Rgb([0,0,0]);
    imageproc::drawing::draw_text(
        &mut img_buf, 
        TEXT_COLOR,
        SIZE/2,
        SIZE/2,
        rusttype::Scale::uniform(1.), 
        &rusttype::Font::try_from_bytes(std::include_bytes!("../Roboto-Regular.ttf")).unwrap(),
        TEXT
    );
    img_buf.save("img_text.png").unwrap();

}
```
`cargo.toml`:
```toml
[package]
name = "test_project"
version = "0.1.0"
authors = ["Jonathan <jonthanwoollettlight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
imageproc = "0.22.0"
rusttype = "0.9.2"
```

This produces:

`img_blank.png`:

<img src="https://user-images.githubusercontent.com/16856679/137155773-2ca10e12-4214-4287-b159-892018a2d2eb.png" height="150">

`img_text.png`:

<img src="https://user-images.githubusercontent.com/16856679/137156020-36a72ad7-ffeb-4f78-bcc0-fac1eb093ac5.png" height="150">

Am I missing something here, or is this a bug?
