### ISSUE TITLE
Request for new crates.io release with `image 0.24` updated type definitions 

### ISSUE THREAD

**Issue by foresterre** [image-rs/imageproc#493]
**Problem**

As `imageproc` depends heavily on type definitions, defined in the `image` crate, users of imageproc are required to match the  `image`-dependency version requirement in `imageproc`. 

In #491, `imageproc` was made compatible with `image 0.24`, which allows users of imageproc to use `image >= 0.24.1` :smile:.

Since the changes of #491 are merged, the image 0.24 compatible version of imageproc can be used via Cargo with:
```toml
[dependencies]
imageproc = { git = "https://github.com/image-rs/imageproc.git" }
``` 

However, crates which depend on imageproc, and are published on crates.io can not yet upgrade, as crates.io requires dependency packages to be also published on crates.io (which [imageproc](https://crates.io/crates/imageproc/versions) with `image >= 0.24` isn't yet).

**Question**

If it would be possible, could a new version of the `imageproc` crate (which includes #491) be published on crates.io?

**Workaround**

I currently use [a forked version](https://crates.io/crates/imageproc-patched/0.22.0-unofficial.1-foresterre) of imageproc, which I published to crates.io (altough I would rather use the offical version ^^):

```toml
[dependencies]
imageproc-patched = { version = "0.22.0-unofficial.1-foresterre" }
```
